# Generated by Django 4.0.2 on 2022-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do Not Show', 'Do Not Show')], max_length=11, null=True),
        ),
    ]
